name: Run WebdriverIO Tests

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

jobs:
  test-e2e:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Load .env variables
        run: echo "$(cat .env)" >> $GITHUB_ENV

      - name: Run WebdriverIO Tests
        env:
          # Defina qualquer variável de ambiente necessária
          NODE_ENV: test
          BASE_URL: ${{ vars.BASE_URL }}
        run: npm run test # Ajuste para o comando que inicia seus testes no WebdriverI
        continue-on-error: true   

      - name: Merge Report
        run: npm run merge-reports # Ajuste ao comando de merge que você usa para o Mochawesom

      - name: Generate Mochawesome Report
        run: npm run generate-mocha # Ajuste ao comando de merge que você usa para o Mochawesome

      - name: Upload Report
        uses: actions/upload-artifact@v4
        with:
          name: mochawesome-report
          path: ./reports/mochawesome/html
