name: Run WebdriverIO Tests

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

jobs:
  test-e2e:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Load .env variables
        run: echo "$(cat .env)" >> $GITHUB_ENV

      - name: Run WebdriverIO Tests
        env:
          NODE_ENV: test
          BASE_URL: ${{ vars.BASE_URL }}
        run: npm run test
        continue-on-error: true

      - name: Merge Mochawesome JSON Reports
        if: always()
        run: |
          mkdir -p ${{ github.workspace }}/reports/mochawesome/json
          npm run merge-reports
          if [ -f "${{ github.workspace }}/reports/mochawesome/json/combined-report.json" ]; then
            echo "Arquivo combined-report.json encontrado e gerado com sucesso."
          else
            echo "Erro: combined-report.json não foi gerado."
            exit 1
          fi

      - name: Generate Mochawesome HTML Report
        if: always()
        run: |
          if [ -f "${{ github.workspace }}/reports/mochawesome/json/combined-report.json" ]; then
            npm run generate-mocha
            if [ -f "${{ github.workspace }}/reports/mochawesome/html/assets" ]; then
              echo "Relatório HTML gerado com sucesso."
            else
              echo "Erro: mochawesome-report.html não foi gerado."
              exit 1
            fi
          else
            echo "Erro: combined-report.json não encontrado, não é possível gerar o HTML."
            exit 1
          fi

      - name: Upload HTML Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: mochawesome-report
          path: ${{ github.workspace }}/reports/mochawesome/html/mochawesome-report.html
