name: Run WebdriverIO Tests

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

jobs:
  test-e2e:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Load .env variables
        run: echo "$(cat .env)" >> $GITHUB_ENV

      - name: Run WebdriverIO Tests
        env:
          NODE_ENV: test
          BASE_URL: ${{ vars.BASE_URL }}
        run: npm run test # Ajuste para o comando que inicia seus testes no WebdriverIO
        continue-on-error: true

      - name: Merge Mochawesome JSON Reports
        if: always()
        run: npm run merge-reports # Comando para mesclar relatórios JSON gerados pelo Mochawesome

      - name: Verificar geração do combined-report.json
        if: always()
        run: |
          echo "Verificando se o arquivo combined-report.json foi gerado..."
          ls -lh ./reports/mochawesome/json
          cat ./reports/mochawesome/json/combined-report.json || echo "Arquivo combined-report.json não encontrado."

      - name: Generate Mochawesome HTML Report
        if: always()
        run: npm run generate-mocha # Comando que converte o relatório combinado em um HTML

      - name: Upload HTML Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: mochawesome-report
          path: ./reports/mochawesome/html/mochawesome-report.html