name: Run WebdriverIO Tests

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

jobs:
  test:
    runs-on: ubuntu-latest
    
    # Defina os serviços necessários, por exemplo, se precisa do Chrome
    services:
      selenium:
        image: selenium/standalone-chrome
        ports:
          - 4444:4444

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Run WebdriverIO Tests
        env:
          # Defina qualquer variável de ambiente necessária
          NODE_ENV: test
          URLBASE: ${{ vars.URLBASE }}
        run: npm run test # Ajuste para o comando que inicia seus testes no WebdriverI

      - name: Merge Report
        run: npm run merge-reports # Ajuste ao comando de merge que você usa para o Mochawesom

      - name: Generate Mochawesome Report
        run: npm run generate-mocha # Ajuste ao comando de merge que você usa para o Mochawesome

      - name: Upload Report
        uses: actions/upload-artifact@v2
        with:
          name: mochawesome-report
          path: ./reports/mochawesome/json/combined-report.json
